[theme]
base="light"
primaryColor="#0F766E"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F6F6"
textColor="#111827"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
